### ISSUE TITLE
'bower error  Invalid Version 2.2.' on install

### ISSUE THREAD

**Issue by connercowling** [johnotander/furtive#47]
Can't seem to get furtive to install furtive via 'bower install --save furtive' due to invalid version error.

    bower furtive#*             not-cached git://github.com/johnotander/furtive.git#*
    bower furtive#*                resolve git://github.com/johnotander/furtive.git#*
    bower furtive#*               download https://github.com/johnotander/furtive/archive/2.2.2.tar.gz
    bower furtive#*                extract archive.tar.gz
    bower furtive#*                  error Invalid Version: 2.2.

    Stack trace:
    TypeError: Invalid Version: 2.2.
        at new SemVer (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\semver\semver.js:273:11)
        at compare (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\semver\semver.js:460:10)
        at Object.neq (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\semver\semver.js:504:10)
        at GitHubResolver.GitResolver._savePkgMeta (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitResolver.js:224:56)
        at GitHubResolver._savePkgMeta (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitHubResolver.js:134:53)
        at _fulfilled (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:834:54)
        at self.promiseDispatch.done (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:863:30)
        at Promise.promise.promiseDispatch (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:796:13)
        at C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
        at runSingle (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:137:13)

    Console trace:
    Error
        at StandardRenderer.error (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
        at Logger.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
        at Logger.emit (events.js:107:17)
        at Logger.emit (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
        at C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:45:20
        at _rejected (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
        at C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
        at Promise.when (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
        at Promise.promise.promiseDispatch (C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
        at C:\Users\xxx\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
    System info:
    Bower version: 1.4.1
    Node version: 0.12.6
    OS: Windows_NT 6.1.7601 x64

**Comment by johnotander** [comment]
Hey, thanks for reporting this! I accidentally committed an invalid version value in the `bower.json` which has now been resolved in version `2.2.3`. You should now be able to:

```sh
bower cache clean
bower install --save furtive
```

And the corrected version, `2.2.3`, should be installed. Let me know if you have any more issues.
